
[functions.procesar-archivo]
enabled = true
verify_jwt = false
import_map = "./functions/procesar-archivo/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/procesar-archivo/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/procesar-archivo/*.html" ]

[functions.webhook-kapso]
enabled = true
verify_jwt = true
import_map = "./functions/webhook-kapso/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/webhook-kapso/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/webhook-kapso/*.html" ]

[functions.recalcular-distancias]
enabled = true
verify_jwt = true
import_map = "./functions/recalcular-distancias/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/recalcular-distancias/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/recalcular-distancias/*.html" ]

[functions.generar-corte-diario]
enabled = true
verify_jwt = true
import_map = "./functions/generar-corte-diario/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generar-corte-diario/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generar-corte-diario/*.html" ]

[functions.kapso-message-failed]
enabled = true
verify_jwt = false
import_map = "./functions/kapso-message-failed/deno.json"
entrypoint = "./functions/kapso-message-failed/index.ts"